# Generated by Django 2.2.4 on 2019-09-10 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0002_searchmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchmodel',
            name='IsTrained',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='Outcome',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='Probability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='RequestedDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
