# Generated by Django 2.2.4 on 2019-09-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0004_auto_20190910_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchmodel',
            old_name='text',
            new_name='SearchText',
        ),
    ]
