# Generated by Django 2.2.4 on 2019-09-29 13:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0005_auto_20190910_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='searchmodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='TrainingModel',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('ArticleText', models.TextField()),
                ('Outcome', models.BooleanField(null=True)),
                ('TrainingDate', models.DateTimeField(default=datetime.datetime.now)),
                ('SearchModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DueDiligenceUI.SearchModel')),
            ],
        ),
    ]
