# Generated by Django 2.2.4 on 2019-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0006_auto_20190929_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchmodel',
            name='IsTrained',
        ),
        migrations.AddField(
            model_name='trainingmodel',
            name='IsTrained',
            field=models.BooleanField(default=0),
        ),
    ]
