# Generated by Django 2.2.6 on 2019-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0007_auto_20190929_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
