# Generated by Django 2.2.6 on 2019-10-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DueDiligenceUI', '0009_auto_20191021_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='Probability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
